export const PAISES_TELEFONO = [
  { iso: "CL", nombre: "Chile", codigo: "+56" },
  { iso: "AR", nombre: "Argentina", codigo: "+54" },
  { iso: "PE", nombre: "Peru", codigo: "+51" },
  { iso: "US", nombre: "Estados Unidos", codigo: "+1" },
  { iso: "CA", nombre: "Canada", codigo: "+1" },
  { iso: "MX", nombre: "Mexico", codigo: "+52" },
  { iso: "BR", nombre: "Brasil", codigo: "+55" },
  { iso: "UY", nombre: "Uruguay", codigo: "+598" },
  { iso: "PY", nombre: "Paraguay", codigo: "+595" },
  { iso: "BO", nombre: "Bolivia", codigo: "+591" },
  { iso: "CO", nombre: "Colombia", codigo: "+57" },
  { iso: "EC", nombre: "Ecuador", codigo: "+593" },
  { iso: "VE", nombre: "Venezuela", codigo: "+58" },
  { iso: "CR", nombre: "Costa Rica", codigo: "+506" },
  { iso: "PA", nombre: "Panama", codigo: "+507" },
  { iso: "ES", nombre: "Espana", codigo: "+34" },
  { iso: "FR", nombre: "Francia", codigo: "+33" },
  { iso: "DE", nombre: "Alemania", codigo: "+49" },
  { iso: "IT", nombre: "Italia", codigo: "+39" },
  { iso: "PT", nombre: "Portugal", codigo: "+351" },
  { iso: "GB", nombre: "Reino Unido", codigo: "+44" },
  { iso: "IE", nombre: "Irlanda", codigo: "+353" },
  { iso: "NL", nombre: "Paises Bajos", codigo: "+31" },
  { iso: "BE", nombre: "Belgica", codigo: "+32" },
  { iso: "CH", nombre: "Suiza", codigo: "+41" },
  { iso: "CN", nombre: "China", codigo: "+86" },
  { iso: "JP", nombre: "Japon", codigo: "+81" },
  { iso: "KR", nombre: "Corea del Sur", codigo: "+82" },
  { iso: "IN", nombre: "India", codigo: "+91" },
  { iso: "AU", nombre: "Australia", codigo: "+61" },
  { iso: "NZ", nombre: "Nueva Zelanda", codigo: "+64" },
  { iso: "ZA", nombre: "Sudafrica", codigo: "+27" },
  { iso: "MA", nombre: "Marruecos", codigo: "+212" },
  { iso: "EG", nombre: "Egipto", codigo: "+20" },
  { iso: "IL", nombre: "Israel", codigo: "+972" },
  { iso: "AE", nombre: "Emiratos Arabes Unidos", codigo: "+971" },
  { iso: "TR", nombre: "Turquia", codigo: "+90" },
];

export function getPaisTelefono(iso = "CL") {
  return PAISES_TELEFONO.find((pais) => pais.iso === iso) || PAISES_TELEFONO[0];
}
