"use client";
import { useCallback, useEffect, useState } from "react";
const labels = { PENDING: "Pendiente de emisión", PROCESSING: "Procesando", RETRY: "Pendiente de reintento", FAILED: "Error de emisión", COMPLETED: "Emitido" };
export default function DocumentJobPanel({ onChanged }) {
  const [jobs, setJobs] = useState([]), [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/billing/document-jobs", { cache: "no-store" }), payload = await response.json(); if (!response.ok) throw new Error(payload.error); setJobs(payload.data || []); }, []);
  useEffect(() => { let active = true; (async () => { try { const response = await fetch("/api/billing/document-jobs", { cache: "no-store" }), payload = await response.json(); if (!response.ok) throw new Error(payload.error); if (active) setJobs(payload.data || []); } catch (error) { if (active) setMessage(error.message); } })(); return () => { active = false; }; }, []);
  const retry = async job => { setMessage(""); const response = await fetch(`/api/billing/documents/${job.document_id}/retry`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ providerScenario: "success" }) }), payload = await response.json(); if (!response.ok) return setMessage(payload.error); setMessage("Reintento procesado correctamente."); await load(); onChanged?.(); };
  const visible = jobs.filter(job => job.status !== "COMPLETED"); if (!visible.length && !message) return null;
  return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold text-amber-950">Procesamiento documental</h3>{message ? <p className="mt-2 text-sm text-amber-900">{message}</p> : null}<div className="mt-2 space-y-2">{visible.map(job => <div key={job.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white p-3 text-sm"><div><strong>{labels[job.status] || job.status}</strong><span className="ml-2 text-slate-500">Intento {job.attempts}/{job.max_attempts}</span>{job.error_message ? <p className="mt-1 text-red-700">{job.error_message}</p> : null}</div>{["FAILED", "RETRY"].includes(job.status) && job.attempts < job.max_attempts ? <button type="button" onClick={() => retry(job)} className="rounded-lg bg-[#3150D8] px-3 py-2 font-semibold text-white">Reintentar emisión</button> : null}</div>)}</div></section>;
}
