"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator, RefreshCcw, X } from "lucide-react";
import ParkFacilDataGrid from "@/components/ui/ParkFacilDataGrid";

const money = (value, currency) => currency === "UF" ? `${new Intl.NumberFormat("es-CL", { maximumFractionDigits:4 }).format(Number(value||0))} UF` : new Intl.NumberFormat("es-CL", { style:"currency", currency:currency||"CLP", maximumFractionDigits:0 }).format(Number(value||0));
const defaultPeriod = () => new Date().toISOString().slice(0,7);

export default function PreinvoiceWorkspace({columns}){
  const [rows,setRows]=useState([]); const [period,setPeriod]=useState(defaultPeriod); const [loading,setLoading]=useState(true);
  const [message,setMessage]=useState(""); const [detail,setDetail]=useState(null);
  const [comment,setComment]=useState(""); const [adjustment,setAdjustment]=useState({amount:"",reason:""});
  const load=useCallback(async(clearMessage=true)=>{setLoading(true);if(clearMessage)setMessage("");try{const response=await fetch(`/api/billing/preinvoices?period=${encodeURIComponent(period)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"No fue posible cargar prefacturas.");setRows(payload.data||[]);}catch(error){setRows([]);setMessage(error.message);}finally{setLoading(false);}},[period]);
  useEffect(()=>{let active=true;(async()=>{try{const response=await fetch(`/api/billing/preinvoices?period=${encodeURIComponent(period)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"No fue posible cargar prefacturas.");if(active)setRows(payload.data||[]);}catch(error){if(active){setRows([]);setMessage(error.message);}}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[period]);
  const calculate=async()=>{setLoading(true);setMessage("");try{const response=await fetch("/api/billing/preinvoices/calculate",{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({period})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"No fue posible calcular.");const blocked=(payload.data?.results||[]).filter(x=>x.status==="BLOCKED");setMessage(blocked.length?`Cálculo incompleto: ${blocked.map(x=>x.message).join(" · ")}`:"Prefacturación calculada correctamente.");await load(false);}catch(error){setMessage(error.message);}finally{setLoading(false);}};
  const openDetail=async(row)=>{const response=await fetch(`/api/billing/preinvoices/${row.id}`,{cache:"no-store"});const payload=await response.json();if(response.ok)setDetail(payload.data);else setMessage(payload.error||"No fue posible abrir el detalle.");};
  const workflow=async(action,body={})=>{const response=await fetch(`/api/billing/preinvoices/${detail.id}/${action}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({version:detail.version,...body})});const payload=await response.json();if(!response.ok){setMessage(payload.error||"No fue posible completar la acción.");return;}await openDetail({id:detail.id});await load(false);};
  const issue=async()=>{const invoiceDate=new Date().toISOString().slice(0,10);const response=await fetch(`/api/billing/preinvoices/${detail.id}/issue`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({invoiceDate})});const payload=await response.json();if(!response.ok){setMessage(payload.error||"No fue posible emitir el documento.");return;}setMessage(`Documento emitido con proveedor Mock: ${payload.data?.folio||payload.data?.documentId||"sin folio"}.`);await openDetail({id:detail.id});await load(false);};
  const addComment=async()=>{await workflow("comments",{text:comment});setComment("");};
  const addAdjustment=async()=>{const origin=detail.lines?.[0];if(!origin){setMessage("Se requiere una línea de origen para registrar el ajuste.");return;}await workflow("adjustments",{type:Number(adjustment.amount)<0?"DISCOUNT":"EXTRA_CHARGE",description:"Ajuste manual autorizado",quantity:1,unit:"unit",unitPrice:Math.abs(Number(adjustment.amount)),currency:detail.moneda,conceptId:origin.concept_id,originalLineId:origin.id,reason:adjustment.reason});setAdjustment({amount:"",reason:""});};
  const mappedColumns=useMemo(()=>[...columns.map(column=>["neto","impuesto","total"].includes(column.key)?{...column,render:(value,row)=>money(value,row.moneda),exportValue:row=>row[column.key]}:column),{key:"acciones",label:"Acciones",width:90,sortable:false,resizable:false,render:(_value,row)=><button type="button" onClick={event=>{event.stopPropagation();openDetail(row);}} className="rounded-lg border border-slate-200 px-3 py-1 font-bold" aria-label={`Acciones ${row.prefactura}`}>•••</button>}],[columns]);
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4">
      <label className="text-sm font-semibold text-[#041E42]">Período<input type="month" value={period} onChange={event=>{setLoading(true);setPeriod(event.target.value);}} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2" /></label>
      <button type="button" onClick={calculate} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-[#3150D8] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Calculator className="h-4 w-4"/> Calcular prefacturación</button>
      <button type="button" onClick={()=>load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold"><RefreshCcw className="h-4 w-4"/> Actualizar</button>
      <p className="text-sm text-slate-600">{loading?"Consultando datos reales…":message||"Doble clic en una prefactura para revisar su origen."}</p>
    </div>
    <ParkFacilDataGrid storageKey="facturacion:prefacturacion" columns={mappedColumns} rows={rows} onRowDoubleClick={openDetail} globalSearchPlaceholder="Buscar en prefacturación..." emptyMessage={message||"No existen prefacturas reales para el período."} exportFilename="facturacion_prefacturacion" exportSheetName="Prefacturación" />
    {detail?<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><section className="max-h-[90vh] w-full max-w-6xl overflow-auto rounded-3xl bg-white p-6 shadow-xl"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#3150D8]">Detalle de prefactura</p><h3 className="mt-1 text-2xl font-bold text-[#041E42]">{detail.prefactura}</h3><p className="text-sm text-slate-600">{detail.cliente} · {detail.rut} · {detail.contrato} · {detail.periodo} · {detail.estado}</p><p className="text-sm">Neto {money(detail.neto,detail.moneda)} · Impuesto {money(detail.impuesto,detail.moneda)} · Total {money(detail.total,detail.moneda)}</p>{detail.moneda==="UF"?<p className="mt-1 rounded-lg bg-amber-50 p-2 text-sm text-amber-800">UF provisional: {detail.ufValue||"pendiente"} · fecha {detail.ufDate||"sin definir"}. Valor UF provisional hasta la emisión definitiva; la UF final corresponderá al día de emisión.</p>:null}</div><button onClick={()=>setDetail(null)} aria-label="Cerrar"><X/></button></div>
      <div className="mt-4 flex flex-wrap gap-2">{detail.estado==="CALCULATED"?<button onClick={()=>workflow("review")} className="rounded-lg bg-[#3150D8] px-3 py-2 text-sm font-semibold text-white">Iniciar revisión</button>:null}{detail.estado==="UNDER_REVIEW"?<><button onClick={()=>workflow("recalculate")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Recalcular</button><button onClick={()=>workflow("approve")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Aprobar</button></>:null}{detail.estado==="APPROVED"?<button onClick={()=>workflow("ready-to-issue")} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Marcar lista para emitir</button>:null}{detail.estado==="READY_TO_ISSUE"?<button onClick={issue} className="rounded-lg bg-[#3150D8] px-3 py-2 text-sm font-semibold text-white">Emitir con Mock</button>:null}{["DRAFT","CALCULATED","UNDER_REVIEW"].includes(detail.estado)?<button onClick={()=>{const reason=window.prompt("Motivo obligatorio de cancelación");if(reason)workflow("cancel",{reason});}} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Cancelar</button>:null}</div>
      <h4 className="mt-6 font-bold text-[#041E42]">Líneas y origen del cobro</h4><div className="mt-2 overflow-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Concepto</th><th className="p-2">Descripción</th><th className="p-2">Cantidad</th><th className="p-2">Precio</th><th className="p-2">Subtotal</th><th className="p-2">Estacionamiento / Device / Origen</th><th className="p-2">Vigencia</th><th className="p-2">Estado</th></tr></thead><tbody>{detail.lines.map(line=><tr key={line.id} className="border-b"><td className="p-2">{line.billable_concepts?.name||line.concept_id}</td><td className="p-2">{line.description}</td><td className="p-2">{line.quantity} {line.unit}</td><td className="p-2">{money(line.unit_price,line.currency)}</td><td className="p-2">{money(line.subtotal,line.currency)}</td><td className="p-2">{line.parkings?.name||line.billing_devices?.name||line.source_type} → {detail.contrato} → {detail.cliente}</td><td className="p-2">{line.valid_from}–{line.valid_to}</td><td className="p-2">{line.line_status}</td></tr>)}</tbody></table></div>
      <div className="mt-6 grid gap-5 lg:grid-cols-3"><section><h4 className="font-bold">Observaciones</h4><div className="mt-2 space-y-2">{(detail.comments||[]).map(x=><p key={x.id} className="rounded-lg bg-slate-50 p-2 text-sm">{x.text}<span className="block text-xs text-slate-500">{new Date(x.created_at).toLocaleString("es-CL")}</span></p>)}</div>{["DRAFT","CALCULATED","UNDER_REVIEW"].includes(detail.estado)?<div className="mt-2"><textarea value={comment} onChange={e=>setComment(e.target.value)} className="w-full rounded-lg border p-2 text-sm" placeholder="Agregar observación"/><button onClick={addComment} className="mt-1 rounded-lg border px-3 py-1 text-sm">Guardar</button></div>:null}</section><section><h4 className="font-bold">Ajustes</h4>{(detail.adjustments||[]).map(x=><p key={x.id} className="mt-2 rounded-lg bg-slate-50 p-2 text-sm">{x.description}: {money(x.amount,x.currency)}<span className="block text-xs">{x.reason} · {x.status}</span></p>)}{["DRAFT","CALCULATED","UNDER_REVIEW"].includes(detail.estado)?<div className="mt-2 space-y-2"><input value={adjustment.amount} onChange={e=>setAdjustment(x=>({...x,amount:e.target.value}))} type="number" className="w-full rounded-lg border p-2 text-sm" placeholder="Monto (+ cargo / - descuento)"/><input value={adjustment.reason} onChange={e=>setAdjustment(x=>({...x,reason:e.target.value}))} className="w-full rounded-lg border p-2 text-sm" placeholder="Motivo obligatorio"/><button onClick={addAdjustment} className="rounded-lg border px-3 py-1 text-sm">Agregar ajuste</button></div>:null}</section><section><h4 className="font-bold">Auditoría</h4><div className="mt-2 space-y-2">{(detail.audit||[]).map(x=><p key={x.id} className="rounded-lg bg-slate-50 p-2 text-xs"><strong>{x.action}</strong> · {new Date(x.created_at).toLocaleString("es-CL")}<span className="block">{x.reason||"Sin motivo adicional"}</span></p>)}</div></section></div>
    </section></div>:null}
  </div>;
}
