"use client";
import { useEffect, useState } from "react";
import { authenticatedFetch } from "@/lib/supabaseBrowser";
const dt = (value) => value ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const money = (value) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value || 0);
const paymentLabels = { DEBIT: "Débito", CREDIT: "Crédito" };
const Info = ({ name, value }) => <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{name}</p><p className="mt-1 font-semibold text-[#041E42]">{value ?? "—"}</p></div>;
export default function OnStreetSessionDetail({ id }) {
  const [data, setData] = useState(null), [error, setError] = useState("");
  useEffect(() => { authenticatedFetch(`/api/on-street-qr/sessions/${id}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body.data); }).catch((cause) => setError(cause.message)); }, [id]);
  if (error) return <p className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>;
  if (!data) return <p>Cargando sesión…</p>;
  const session = data.session, initial = data.transactions.find((item) => item.id === session.payment_transaction_id);
  const timeline = [{ name: "QR consultado / intención creada", at: initial?.created_at },{ name: "Webpay iniciado", at: initial?.redirected_at },{ name: initial?.status === "COMMITTED" ? "Pago confirmado" : "Pago rechazado", at: initial?.committed_at || initial?.failed_at },{ name: "Sesión activada", at: session.started_at },...data.extensions.map((item) => ({ name: `Extensión +${item.additional_minutes} min`, at: item.created_at })),{ name: session.status === "CLOSED" ? "Sesión cerrada" : "Vencimiento programado", at: session.ended_at || session.expires_at }].filter((item) => item.at);
  return <div className="space-y-5"><section className="rounded-2xl bg-white p-5"><h2 className="text-xl font-bold">{session.operational_number}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info name="Estado" value={session.status}/><Info name="Ubicación" value={session.location.label}/><Info name="Inicio" value={dt(session.started_at)}/><Info name="Vencimiento" value={session.expires_at?dt(session.expires_at):"Sin vencimiento"}/><Info name="Cierre" value={dt(session.ended_at)}/><Info name="Minutos" value={session.purchased_minutes?`${session.purchased_minutes} min`:"—"}/><Info name="Monto pagado" value={money(session.amount)}/><Info name="Teléfono" value={session.phone}/></div></section><section className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Pago</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info name="Proveedor" value="Transbank Webpay"/><Info name="Medio" value={paymentLabels[initial?.payment_type] || "No informado"}/><Info name="Monto" value={money(initial?.amount)}/><Info name="Buy Order" value={initial?.buy_order}/><Info name="Código autorización" value={initial?.authorization_code}/><Info name="Fecha de pago" value={dt(initial?.committed_at)}/><Info name="Estado transacción" value={initial?.status}/></div></section><section className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Trazabilidad</h2><ol className="mt-4 border-l-2 border-[var(--pf-color-onstreet-border)] pl-5">{timeline.map((item, index) => <li key={`${item.name}-${index}`} className="relative pb-4"><span className="absolute -left-[1.6rem] top-1 h-3 w-3 rounded-full bg-[var(--pf-color-onstreet-primary)]"/><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-500">{dt(item.at)}</p></li>)}</ol></section></div>;
}
