"use client";

import { useState } from "react";
import { LoaderCircle, Plus, X } from "lucide-react";
import { authenticatedFetch } from "@/lib/supabaseBrowser";

const initial = { code: "", name: "", description: "", status: "draft", type: "monthly_subscription", currency: "UF", billingMode: "monthly", monthlyFee: "", annualFee: "", implementationFee: "", transactionFee: "", deviceFee: "", parkingFee: "", supportFee: "", discountPercentage: "", minimumMonthlyCharge: "", includedParkings: "", includedDevices: "", includedUsers: "", modules: "", equipment: "", notes: "" };
const moneyFields = [["monthlyFee","Tarifa mensual"],["annualFee","Tarifa anual"],["implementationFee","Implementación"],["transactionFee","Por transacción"],["deviceFee","Por dispositivo"],["parkingFee","Por estacionamiento"],["supportFee","Soporte"],["minimumMonthlyCharge","Mínimo mensual"]];

export default function PlanCreateModal({ onCreated }) {
  const [open,setOpen]=useState(false); const [form,setForm]=useState(initial); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const change=(key,value)=>setForm((current)=>({...current,[key]:value}));
  async function submit(event){event.preventDefault();setSaving(true);setError("");try{const response=await authenticatedFetch("/api/planes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)throw new Error(body.error||"No fue posible crear el plan.");onCreated(body.data);setForm(initial);setOpen(false);}catch(e){setError(e.message);}finally{setSaving(false);}}
  return <><button type="button" onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-[#3150D8] px-4 py-2 text-sm font-semibold text-white hover:bg-[#1E5EFF]"><Plus className="h-4 w-4"/>Crear plan</button>{open?<div className="fixed inset-0 z-50 overflow-y-auto bg-[#041E42]/65 p-4 backdrop-blur-sm"><form onSubmit={submit} className="mx-auto my-6 max-w-4xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#3150D8] p-5 text-white"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-200">Tarifas y planes</p><h2 className="mt-1 text-xl font-bold">Crear plan comercial</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"><X/></button></header><div className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-3">
    <Field label="Código"><input required value={form.code} onChange={e=>change("code",e.target.value)} className="input" placeholder="PF-PLAN-005"/></Field><Field label="Nombre"><input required value={form.name} onChange={e=>change("name",e.target.value)} className="input"/></Field><Field label="Estado"><select value={form.status} onChange={e=>change("status",e.target.value)} className="input"><option value="draft">Borrador</option><option value="active">Activo</option><option value="inactive">Inactivo</option><option value="archived">Archivado</option></select></Field>
    <Field label="Tipo"><select value={form.type} onChange={e=>change("type",e.target.value)} className="input"><option value="monthly_subscription">Suscripción mensual</option><option value="per_transaction">Por transacción</option><option value="per_parking">Por estacionamiento</option><option value="equipment_bundle">Equipamiento</option><option value="implementation_only">Implementación</option><option value="custom">Personalizado</option></select></Field><Field label="Moneda"><select value={form.currency} onChange={e=>change("currency",e.target.value)} className="input"><option>UF</option><option>CLP</option><option>USD</option></select></Field><Field label="Modalidad comercial del plan"><select value={form.billingMode} onChange={e=>change("billingMode",e.target.value)} className="input"><option value="monthly">Mensual</option><option value="annual">Anual</option><option value="one_time">Pago único</option><option value="per_transaction">Por transacción</option><option value="mixed">Mixta</option></select></Field>
    <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-slate-700 sm:col-span-2 lg:col-span-3"><p className="font-bold text-[#102A5E]">Alcance de la Ley 20.967</p><p className="mt-1">Estos valores corresponden al contrato comercial de ParkFacil. La tarifa cobrada al conductor se configura por estacionamiento y, para estadías inferiores a 24 horas, solo admite minuto efectivo o tramos vencidos sin redondeo al alza.</p></div>
    {moneyFields.map(([key,label])=><Field key={key} label={label}><input type="number" min="0" step="0.01" value={form[key]} onChange={e=>change(key,e.target.value)} className="input"/></Field>)}<Field label="Descuento (%)"><input type="number" min="0" max="100" step="0.01" value={form.discountPercentage} onChange={e=>change("discountPercentage",e.target.value)} className="input"/></Field>{[["includedParkings","Estacionamientos incluidos"],["includedDevices","Dispositivos incluidos"],["includedUsers","Usuarios incluidos"]].map(([key,label])=><Field key={key} label={label}><input type="number" min="0" value={form[key]} onChange={e=>change(key,e.target.value)} className="input"/></Field>)}
    <Field label="Descripción" wide><textarea required rows="3" value={form.description} onChange={e=>change("description",e.target.value)} className="input"/></Field><Field label="Módulos (separados por coma)" wide><input value={form.modules} onChange={e=>change("modules",e.target.value)} className="input"/></Field><Field label="Equipamiento (separado por coma)" wide><input value={form.equipment} onChange={e=>change("equipment",e.target.value)} className="input"/></Field>{error?<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2 lg:col-span-3">{error}</p>:null}
  </div><footer className="flex justify-end gap-3 border-t bg-slate-50 p-4"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Cancelar</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#3150D8] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{saving?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}{saving?"Creando plan…":"Crear plan"}</button></footer></form></div>:null}</>;
}
function Field({label,wide,children}){return <label className={`text-sm font-semibold text-slate-600 ${wide?"sm:col-span-2 lg:col-span-3":""}`}><span className="mb-1.5 block">{label}</span>{children}</label>}
