import { LayoutGrid, BarChart3, ParkingSquare, ShieldCheck, KeyRound, Wallet, WalletCards, BadgeDollarSign, Layers, Users, Handshake, RadioTower, Monitor, FileChartColumnIncreasing, Settings2, Plug2, BookOpen, Calculator, SlidersHorizontal, ScanLine, TicketPercent } from "lucide-react";

export const navigationItems = [
  { href: "/", label: "Inicio", icon: LayoutGrid, active: true },
  { href: "/modelo-dashboard", label: "Dashboard", icon: BarChart3 },
  { href: "/data-entry", label: "Data Entry", icon: ScanLine },
  { href: "/operacion", label: "Operación", icon: ParkingSquare },
  { href: "/estacionamientos", label: "Estacionamientos", icon: ShieldCheck },
  { href: "/seguridad", label: "Seguridad", icon: KeyRound, requiresModule: "seguridad" },
  { href: "/recaudacion", label: "Recaudación", icon: Wallet },
  { href: "/recaudacion#medios-de-pago", label: "Medios de Pago", icon: WalletCards },
  { href: "/empresas", label: "Empresas", icon: Users },
  { href: "/usuarios", label: "Usuarios", icon: Users },
  { href: "/modelo-gestion-modulos", label: "Gestión de módulos", icon: SlidersHorizontal },
  { href: "/contratos", label: "Contratos", icon: Handshake },
  { href: "/abonados", label: "Abonados y Credenciales", icon: KeyRound },
  { href: "/administracion-tarifas", label: "Tarifas", icon: BadgeDollarSign },
  { href: "/tarifas", label: "Planes", icon: Layers },
  { href: "/cupones", label: "Cupones y descuentos", icon: TicketPercent },
  { href: "/convenios", label: "Convenios", icon: Handshake },
  { href: "/simulador-tarifas", label: "Simulador de tarifas", icon: Calculator },
  { href: "/dispositivos", label: "Dispositivos", icon: RadioTower },
  { href: "/monitoreo", label: "Monitoreo", icon: Monitor },
  { href: null, label: "Reportes", icon: FileChartColumnIncreasing, future: true },
  { href: null, label: "Administración", icon: Settings2, future: true },
  { href: null, label: "Integraciones", icon: Plug2, future: true },
  { href: "/documentos", label: "Documentación", icon: BookOpen },
];
