"use client";
import { Fragment, useCallback, useEffect, useState } from "react";
import { authenticatedFetch } from "@/lib/supabaseBrowser";
import { formatDuration, remainingSeconds } from "@/lib/onStreetPilot.mjs";
const dt = (v) => v ? new Intl.DateTimeFormat("es-CL", { dateStyle: "short", timeStyle: "short" }).format(new Date(v)) : "—";
const money = (v) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(v || 0);
export default function ParkingQrSessionsPanel({ parking }) {
  const [rows, setRows] = useState([]), [error, setError] = useState(""), [now, setNow] = useState(0);
  const load = useCallback(async () => { try { const r = await authenticatedFetch(`/api/estacionamientos/${parking.code}/sesiones-qr`), b = await r.json(); if (!r.ok) throw new Error(b.error); setRows(b.data || []); } catch (e) { setError(e.message); } }, [parking.code]);
  useEffect(() => { const t = setTimeout(() => void load(), 0); return () => clearTimeout(t); }, [load]);
  useEffect(() => { const t = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(t); }, []);
  const headers = ["Sesión", "Sector", "Calle", "Tramo", "Teléfono", "Inicio", "Tiempo inicial", "Tiempo total", "Vencimiento", "Restante", "Tarifa", "Monto total", "Ext.", "Estado"];
  return <section className="rounded-3xl bg-white p-5"><h2 className="text-xl font-bold">Sesiones QR</h2><p className="text-sm text-slate-500">Prepago simulado · {parking.name}</p>{error ? <p className="text-rose-700">{error}</p> : null}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-sm"><thead className="bg-[#041E42] text-white"><tr>{headers.map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows.map((r) => <Fragment key={r.id}><tr className="border-b"><td className="p-3 font-mono">{r.id.slice(0, 8)}</td><td className="p-3">{r.sector}</td><td className="p-3">{r.street}</td><td className="p-3">{r.segment}</td><td className="p-3">{r.phone}</td><td className="p-3">{dt(r.startedAt)}</td><td className="p-3">{r.originalMinutes} min<br/><span className="text-xs text-slate-500">{money(r.initialSimulatedAmount)}</span></td><td className="p-3 font-bold">{r.purchasedMinutes} min</td><td className="p-3">{dt(r.expiresAt)}</td><td className="p-3">{r.status !== "ACTIVE" ? (r.status === "EXPIRED" ? "Vencido" : "—") : r.expiresAt ? formatDuration(remainingSeconds(r.expiresAt, now)) : "Sin vencimiento"}</td><td className="p-3">{money(r.ratePerMinute)}/min</td><td className="p-3 font-bold">{money(r.simulatedAmount)}</td><td className="p-3">{r.extensionCount}</td><td className="p-3 font-bold">{r.status}</td></tr>{r.extensions.length ? <tr className="border-b bg-slate-50"><td colSpan={14} className="p-3"><b>Trazabilidad de extensiones</b><div className="mt-2 grid grid-cols-7 gap-3 text-xs font-bold"><span>Fecha/hora</span><span>Minutos</span><span>Tarifa</span><span>Monto</span><span>Vencimiento anterior</span><span>Nuevo vencimiento</span><span>Sesión asociada</span></div>{r.extensions.map((e) => <div key={e.id} className="mt-1 grid grid-cols-7 gap-3 text-xs"><span>{dt(e.createdAt)}</span><span>+{e.additionalMinutes} min</span><span>{money(e.ratePerMinute)}/min</span><span>{money(e.simulatedAmount)}</span><span>{dt(e.previousExpiresAt)}</span><span>{dt(e.newExpiresAt)}</span><span className="font-mono">{e.sessionId.slice(0, 8)}</span></div>)}</td></tr> : null}{r.notifications?.length ? <tr className="border-b bg-blue-50"><td colSpan={14} className="p-3"><b>Avisos SMS</b>{r.notifications.map((n) => <div key={n.id} className="mt-1 grid grid-cols-4 gap-3 text-xs"><span>{dt(n.scheduledAt)}</span><span>{n.type === "EXPIRING_SOON" ? "Vence en 10 minutos" : "Tiempo expirado"}</span><span>{n.sentAt ? dt(n.sentAt) : "—"}</span><b>{n.status}</b></div>)}</td></tr> : null}</Fragment>)}</tbody></table></div></section>;
}
