"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { authenticatedFetch } from "@/lib/supabaseBrowser";
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
export default function ShiftClosureForm({shiftId}){
  const router=useRouter();const [data,setData]=useState(null);const [error,setError]=useState("");const [observations,setObservations]=useState("");const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{authenticatedFetch(`/api/turnos/${shiftId}/cerrar`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b.data);}).catch(e=>setError(e.message));},[shiftId]);
  async function close(){if(!window.confirm("¿Confirmas el cierre definitivo del turno? Esta acción no se puede deshacer."))return;setSubmitting(true);setError("");try{const response=await authenticatedFetch(`/api/turnos/${shiftId}/cerrar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({observations,confirm:true})});const body=await response.json();if(!response.ok)throw new Error(body.error);router.push(`/cierres-turno/${body.data.cierre.id}`);}catch(e){setError(e.message);}finally{setSubmitting(false);}}
  if(!data&&!error)return <Panel>Consultando turno…</Panel>;
  return <div className="space-y-4">{error&&<p role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{data&&<><Block title="Información del turno"><Grid items={[["Operador",data.operator.id],["Fecha",data.shift.date],["Hora de inicio",formatDate(data.shift.openedAt||data.shift.scheduledStart)],["Hora de cierre","Se asignará al confirmar"]]}/></Block><Block title="Área asignada"><Grid items={[["Sector",data.sector.name],["Calle",data.street.name],["Tramo",`${data.street.name} ${data.assignment.numberFrom}–${data.assignment.numberTo}`],["Plazas",`${data.assignment.assignedSpaces} plazas asignadas`]]}/></Block><Block title="Resumen operacional">{data.summary?<Grid items={[["Monto recaudado",money.format(data.summary.collectedAmount)],["Vehículos pagados",data.summary.paidVehicles],["Vehículos pendientes",data.summary.pendingVehicles],["Vehículos anulados",data.summary.cancelledVehicles]]}/>:<p className="text-sm text-amber-800">{data.summaryError.message}</p>}</Block><Block title="Observaciones"><textarea maxLength="1000" value={observations} onChange={e=>setObservations(e.target.value)} rows="4" className="w-full rounded-2xl border border-slate-200 p-3 text-sm outline-none focus:border-[#3150D8]" placeholder="Observaciones opcionales del operador" /></Block><div className="flex justify-end gap-3"><Link href="/estacionamientos" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold">Cancelar</Link><button onClick={close} disabled={submitting} className="rounded-full bg-[#3150D8] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{submitting?"Cerrando…":"Cerrar turno"}</button></div></>}</div>;
}
function Panel({children}){return <div className="rounded-3xl border border-slate-200 bg-white p-6">{children}</div>};function Block({title,children}){return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-[#041E42]">{title}</h2><div className="mt-3">{children}</div></section>};function Grid({items}){return <dl className="grid gap-3 sm:grid-cols-2">{items.map(([k,v])=><div key={k} className="rounded-2xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-1 font-semibold text-[#041E42]">{v??"No disponible"}</dd></div>)}</dl>};function formatDate(v){if(!v)return"No disponible";const d=new Date(v);return Number.isNaN(d.valueOf())?v:new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short",timeZone:"America/Santiago"}).format(d);}
