"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { authenticatedFetch } from "@/lib/supabaseBrowser";
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
export default function ShiftClosureReceipt({closureId}){
  const [closure,setClosure]=useState(null),[error,setError]=useState(""),[format,setFormat]=useState("standard");
  useEffect(()=>{authenticatedFetch(`/api/cierres-turno/${closureId}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setClosure(b.data);}).catch(e=>setError(e.message));},[closureId]);
  function print(next){setFormat(next);setTimeout(()=>window.print(),0);}
  if(error)return <p role="alert" className="rounded-2xl bg-rose-50 p-4 text-rose-800">{error}</p>;if(!closure)return <p>Consultando comprobante…</p>;
  return <><div className="no-print mb-4 flex flex-wrap gap-2"><Link href="/estacionamientos" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold">Volver</Link><button onClick={()=>print("thermal")} className="rounded-full border border-[#3150D8] px-4 py-2 text-sm font-semibold text-[#3150D8]">Imprimir recibo térmico</button><button onClick={()=>print("standard")} className="rounded-full bg-[#3150D8] px-4 py-2 text-sm font-semibold text-white">Imprimir formato estándar</button></div><article className={`shift-receipt ${format}`}><header className="text-center"><p className="text-sm font-semibold">{closure.companyName}</p><p>{closure.parkingName}</p><h1 className="mt-2 text-xl font-bold">Cierre de turno</h1><p className="text-xs">Folio {closure.folio}</p></header><ReceiptSection title="Información del turno" rows={[["Operador",closure.operatorName],["Fecha",closure.shiftDate],["Inicio",date(closure.actualStartAt)],["Cierre",date(closure.actualCloseAt)],["Sector",closure.sectorName],["Calle",closure.streetName],["Desde",closure.numberFrom],["Hasta",closure.numberTo],["Plazas",`${closure.assignedSpaces} plazas asignadas`]]}/><ReceiptSection title="Resumen operacional" rows={[["Monto recaudado",money.format(closure.collectedAmount)],["Vehículos pagados",closure.paidVehicles],["Vehículos pendientes",closure.pendingVehicles],["Vehículos anulados",closure.cancelledVehicles]]}/>{closure.observations&&<ReceiptSection title="Observaciones" rows={[["",closure.observations]]}/>}<footer className="mt-5 border-t border-dashed border-slate-400 pt-3 text-center text-xs"><p>Generado {date(closure.createdAt)}</p><p>Código verificable: {closure.folio}</p></footer></article><style jsx global>{`@media screen{.shift-receipt{margin:auto;border:1px solid #e2e8f0;border-radius:20px;background:white;padding:24px}.shift-receipt.standard{max-width:760px}.shift-receipt.thermal{width:50mm;border-radius:0;padding:3mm;font-size:11px}}@media print{body *{visibility:hidden}.shift-receipt,.shift-receipt *{visibility:visible}.shift-receipt{position:absolute;inset:0;margin:0!important;border:0!important;border-radius:0!important;box-shadow:none!important;color:#000!important;background:#fff!important;break-inside:avoid}.shift-receipt.thermal{page:thermal;width:42mm;padding:2mm;font-size:9pt}.shift-receipt.standard{page:standard;width:auto;max-width:none;padding:10mm}.no-print{display:none!important}}@page thermal{size:50mm auto;margin:2mm}@page standard{size:A4 portrait;margin:12mm}`}</style></>;
}
function ReceiptSection({title,rows}){return <section className="mt-5 break-inside-avoid"><h2 className="border-b border-slate-300 pb-1 text-sm font-bold">{title}</h2><dl className="mt-2 space-y-1">{rows.map(([k,v],i)=><div key={`${k}-${i}`} className="flex justify-between gap-3"><dt className="text-slate-600">{k}</dt><dd className="text-right font-semibold">{v}</dd></div>)}</dl></section>}function date(v){return new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short",timeZone:"America/Santiago"}).format(new Date(v));}
